export const MOVIES_LIST ='http://localhost:4000/movies'
export const MOVIE_ID ='http://localhost:4000/movies/'
export const MOVIE_FILTER ='http://localhost:4000/movies?filter='
export const MOVIE_SEARCH = 'http://localhost:4000/movies'
export const MOVIE_DROPDOWN = 'http://localhost:4000/movies?sortBy=budget&sortOrder=desc'
